# Generated by Django 4.2.26 on 2025-11-10 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Walk',
        ),
    ]
